### ISSUE TITLE
Prepare for full Alpha website go live (24/11)

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#436]
To take place between 20-21/11, this is the final prep for the full website to go live on Monday 24/11.

# Checklist for go-live
(items marked with **NB** are non-blocking)

## Website
* [x] #439
* [x] OpenAddressesUK/theodolite#13
* [x] OpenAddressesUK/theodolite#14
* [x] OpenAddressesUK/theodolite#15

## Contents
- [x] @giacecco's completion of #442, #443 
- [ ] **NB** @giacecco and @peterkwells check robustness of licence statements in download page and DCAT
- [x] **NB** @giacecco to update #449 and #443 to reference actual Open Addresses' launch date (we shouldn't publish the data before OA officially exists as a company)
- [x] rename the downloadable dataset files to reference the exact launch date and change http://openaddressesuk.org/download/ accordingly
- [x] @giacecco to update documentation with real provenance example, using the team's latest format 
- [x] @peterkwells to adapt contents for Alpha launch and check consistency with what was written for #442 
- [x] @peterkwells have we thought of arranging some time from Legal to have a read of the website before launch?
- [ ] @peterkwells' requests on 12/12 described at https://github.com/OpenAddressesUK/openaddressesuk.github.io/issues/15

## Applications
- [x] #437 and test full download
- [x] #457
- [x] @Floppy and @Pezholio review of software components being deployed for go-live: documentation of known issues / temporary arrangements that OA team needs being aware of (pretend someone else than you was asked to address an issue with the live environment) and general tidying up (suitable log verbosity etc.)
- [ ] @murraydata to do testing samples of published data through both publishing APIs and downloadable version, to check that data appears consistent with expectations

## Infrastructure
- [x] @pikesley to inventory deployment resources (see also [here](https://docs.google.com/a/openaddress.es/spreadsheets/d/1Z267PvXDtXtRV4kSNHewpl-ulxUPAA_3ND2aI9GSwaw/edit?usp=sharing)), kill temporary components, harden security if necessary, general tidying up, hand over passwords / keys etc to OA team
 
## Actual go-live
- [x] Point openaddressesuk.org to theodolite
- [x] Redirect alpha. to root domain

We will wait to know from Jeni when it is best to schedule making the raw database EC2 instance into something less temporary. In general, I would like the ODI Team to have their innovation week as planned.
