### ISSUE TITLE
Outsourced website updates

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#630]
This is an overview ticket for the following bits of work:

* [x] Split startups page in two: #611
* [ ] Create improved server-side events page based on Phil's design: #617
* [ ] More flexible tagging for which people are in which teams: #601 
* [x] Three new nodes types: #587
* [ ] Fix title editing bug: #599

**Comment by gilesdring** [comment]
Will take a look at these in more detail later today and come back to you via email.

**Comment by langphil** [comment]
Any updates on this?

**Comment by langphil** [comment]
Adding additional tasks (wishlist) **UPDATING**

*[] SEO / Metadata implementation #647
