### ISSUE TITLE
Improve portal crawler tool

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#637]
@pkqk can you link the ODC tickets?

**Comment by pkqk** [comment]
Smaller tasks:
  - [ ] theodi/open-data-certificate#1140 reattempt a certificate generation if it fails.
  - [ ] theodi/open-data-certificate#1119 a more detailed report on a certification campaign

Larger tasks:
  - [ ] theodi/open-data-certificate#1036 make certification campaigns rerunnable
  - [ ] I also have designs in my head for how to make it so this doesn't need to be run by a dev and can just be a task that an odc admin or member can start running.
