### ISSUE TITLE
Meta-issue for website fixes

### ISSUE THREAD

**Issue by gilesdring** [theodi/shared#671]
Taken from comment to #630

* [ ] SEO / Metadata implementation #647 
* [ ] Create and register sitemap for theodi.org #461 
* [ ] Remove archived items from theodi.org #648 
* [ ] Third level navigation implementation #649 
* [ ] Retrospectively adding tags to existing (published) artefacts #347 
* [ ] Homepage: embedding of video content (iframe) #650 
* [ ] ODI Homepage: hero image carousel #651 
* [ ] Move courses page to server side #652 
* [ ] Bypassing the 2nd pair of eyes process on "new editions" of artefacts #653 
* [ ] Nodes websites blog posts - RSS integration into theodi.org #655

**Comment by dicknorris** [comment]
Is this now sitting with production @langphil ?
