### ISSUE TITLE
Fix membership issues

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#819]
Things to do:

* [x] Minor text change to membership emails: https://github.com/theodi/member-directory/issues/638
* [x] Sponsor/partner changes for two organisations: https://github.com/theodi/member-directory/issues/631
* [x] Check Deutsche Bank membership creation status and possible failure: https://github.com/theodi/member-directory/issues/633
* [x] Welcome email for Bulmer: https://github.com/theodi/member-directory/issues/624
* [x] Investigate missing member records; could all be related.
  * [x] https://github.com/theodi/member-directory/issues/637
  * [x] https://github.com/theodi/member-directory/issues/636
  * [x] https://github.com/theodi/member-directory/issues/632

@juliehitgub has information on all these if necessary. Processing queues were stalled over xmas by stuck jobs. They are now clear, but that may have caused some of these issues. Julie can also say if there are any further issues we need to look at.

Note also that member directory has its own huboard at https://huboard.com/theodi/member-directory

**Comment by Floppy** [comment]
@juliehitgub this lot is all done now. Can you check things from your end, make sure you're happy? I also changed the bcc list to just go to members@ to remove andrea and clara from the list. I suspect that was causing you to get extra emails.

**Comment by Juliehitgub** [comment]
Thanks James.

I've been through them and it looks to me all the fixes have worked; the ID
numbers are in, Welcome Email has new sign off etc. Good idea to take
Andrea and Clara off the list, makes sense.

Rachel has told me Stuart will help me with this ongoing and she has some
new requests of things to do, shall I still create Github tickets for any
help we need?

Julie

Julie McMahon, Membership Administrator
+44 (0) 20 3598 9395

The Open Data Institute, 65 Clifton Street, London EC2A 4JE
<http://www.theodi.org/>
